# Generated by Django 3.2.4 on 2021-07-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_date',)},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='published_date',
            new_name='publish_date',
        ),
    ]
